### ISSUE TITLE
Day of the week in french (Locale)

### ISSUE THREAD

**Issue by pierrebed** [soberstadt/simple-clock-widget#6]
Hi, I'm using simple-clock-widget for Übersicht. I LOVE it. Thank you VERY much.

I'd like to see the week day in french (it is my prefered and local system on my Mac OS 11.3.1) but could't find out how to modifiy you script to do so. Obviously: I'm not a developper....

Can you help me?

Best regards from Switzerland

Pierre

**Comment by soberstadt** [comment]
If you enable `showDate` in the widget config, does it include the day of the week?

In this line, it's the `%a` part:
https://github.com/soberstadt/simple-clock-widget/blob/82740e37e5d1ec7b43aacd675b133b4abe8564d0/simple-clock.widget/index.coffee#L15

**Comment by pierrebed** [comment]
Yes I did (cf screenshot)

I’d like it in french but can’t fond out how







Pierre Bédat
Ostéopathe O.S. / CDS - Étiopathe

16, rue de Rive
1204 Genève / Suisse
☎️ +41 (0)22 735 11 55
***@***.***
🖥  www.bédat.com

**Comment by soberstadt** [comment]
looks like your screenshot didn't attach via email. If your system is in French I would assume the day should be too. If not, I might not be much help :(

**Comment by pierrebed** [comment]
Oh on my machine the secreenshot is attached….

Don’t worry, it’s not a problem with the name of the day in english. It’s a detail.

Yes my system is in french and the day should be too. But it’s not  :D

Thank you very much for your answer.

Best regards.

Pierre






Pierre Bédat
Ostéopathe O.S. / CDS - Étiopathe

16, rue de Rive
1204 Genève / Suisse
☎️ +41 (0)22 735 11 55
***@***.***
🖥  www.bédat.com
